#!/bin/sh

export EDITOR="nvim"
export BROWSER="firefox"

# Text editor
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount sv dnf updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \

# DNF custom alias
alias \
	alias up="dnf up" \
	alias in="dnf in" \

# my custom alias
alias \
	vite="npm create vite@latest" \
	alias pwastudio="npm init @magento/pwa" \
	alias bash="bash --init-file ~/.config/bash/.bashrc" \
	alias yarn="yarn --use-yarnrc ~/.config/yarn/.yarnrc" \
	alias dotfile="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	alias yw="yarn watch" \
	alias yd="yarn dev" \
	alias pyw="PORT=5555 yarn watch" \
