#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh &
xrandr --output Virtual-1 --mode 1920x1080 &
feh --bg-fill /home/long/pictures/wallpapers/gonic.jpg & # replace with your wallpaper
picom &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^5'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


